# Generated by Django 3.1.4 on 2020-12-31 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='completed_episodes',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='episodes',
        ),
    ]
